### ISSUE TITLE
Update NPM Package

### ISSUE THREAD

**Issue by jeresig** [inxilpro/mongoose-diff#3]
Hello! It appears as if the package on NPM is out of date (it's pointing to 0.1, rather than the current 0.2). https://www.npmjs.com/package/mongoose-diff A quick `npm publish` should fix that! Thank you.

**Comment by inxilpro** [comment]
Done!

**Comment by jeresig** [comment]
@inxilpro Excellent, thank you!

**Comment by inxilpro** [comment]
Are you using this on a project?

**Comment by jeresig** [comment]
@inxilpro Yep! I'm experimenting with it for a project of mine - nothing public yet. Still trying to figure out if this meets my needs. Will definitely let you know if I have any questions/suggestions, though!
